(in-package #:cl-lore)


(defgeneric scan-element (output element parents))
(defgeneric process-element (generator output element parents))
(defgeneric push-stack (desc obj stack))
(defgeneric pop-stack (stack))
(defgeneric empty-stack-p (stack))
(defgeneric front-stack (stack))
(defgeneric push-children (tree-node children))
(defgeneric save-output (output))
(defgeneric make-output (generator &rest initargs))
(defgeneric add-to-index (output element parents))
(defgeneric before-trait (generator output trait parents))
(defgeneric after-trait (generator output trait parents))
(defgeneric has-childrens (tree))
